// <auto-generated />
namespace StartCinema.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class TableImage2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TableImage2));
        
        string IMigrationMetadata.Id
        {
            get { return "201904081505255_TableImage2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
